#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.
*/
#ifndef _CFFI_USE_EMBEDDING
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47

#define _CFFI__NUM_PRIM         48
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, CTypeDescrObject *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, CTypeDescrObject *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, CTypeDescrObject *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, CTypeDescrObject *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, CTypeDescrObject *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(CTypeDescrObject *, PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, CTypeDescrObject *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _CFFI_NUM_EXPORTS 26

typedef struct _ctypedescr CTypeDescrObject;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (CTypeDescrObject *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include <evmjit.h>

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 66), // enum evm_code_status()(struct evm_instance *, enum evm_mode, struct evm_uint256be)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 72), // struct evm_instance *
/*  2 */ _CFFI_OP(_CFFI_OP_ENUM, 2), // enum evm_mode
/*  3 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // struct evm_uint256be
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION, 69), // int()(struct evm_instance *, char const *, char const *)
/*  6 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  7 */ _CFFI_OP(_CFFI_OP_POINTER, 64), // char const *
/*  8 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int64_t()(struct evm_env *, enum evm_call_kind, int64_t, struct evm_uint160be, struct evm_uint256be, uint8_t const *, size_t, uint8_t *, size_t)
/* 11 */ _CFFI_OP(_CFFI_OP_POINTER, 70), // struct evm_env *
/* 12 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // enum evm_call_kind
/* 13 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 23), // int64_t
/* 14 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // struct evm_uint160be
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 16 */ _CFFI_OP(_CFFI_OP_POINTER, 77), // uint8_t const *
/* 17 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28), // size_t
/* 18 */ _CFFI_OP(_CFFI_OP_POINTER, 77), // uint8_t *
/* 19 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // struct evm_instance *()(union evm_variant(*)(struct evm_env *, enum evm_query_key, union evm_variant), void(*)(struct evm_env *, enum evm_update_key, union evm_variant, union evm_variant), int64_t(*)(struct evm_env *, enum evm_call_kind, int64_t, struct evm_uint160be, struct evm_uint256be, uint8_t const *, size_t, uint8_t *, size_t))
/* 22 */ _CFFI_OP(_CFFI_OP_POINTER, 40), // union evm_variant(*)(struct evm_env *, enum evm_query_key, union evm_variant)
/* 23 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // void(*)(struct evm_env *, enum evm_update_key, union evm_variant, union evm_variant)
/* 24 */ _CFFI_OP(_CFFI_OP_POINTER, 10), // int64_t(*)(struct evm_env *, enum evm_call_kind, int64_t, struct evm_uint160be, struct evm_uint256be, uint8_t const *, size_t, uint8_t *, size_t)
/* 25 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION, 73), // struct evm_interface()(void)
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 28 */ _CFFI_OP(_CFFI_OP_FUNCTION, 75), // struct evm_result()(struct evm_instance *, struct evm_env *, enum evm_mode, struct evm_uint256be, uint8_t const *, size_t, int64_t, uint8_t const *, size_t, struct evm_uint256be)
/* 29 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 11),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 34 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 35 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 23),
/* 36 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 38 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 39 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 40 */ _CFFI_OP(_CFFI_OP_FUNCTION, 43), // union evm_variant()(struct evm_env *, enum evm_query_key, union evm_variant)
/* 41 */ _CFFI_OP(_CFFI_OP_NOOP, 11),
/* 42 */ _CFFI_OP(_CFFI_OP_ENUM, 3), // enum evm_query_key
/* 43 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 6), // union evm_variant
/* 44 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 45 */ _CFFI_OP(_CFFI_OP_FUNCTION, 88), // void()(struct evm_env *, enum evm_update_key, union evm_variant, union evm_variant)
/* 46 */ _CFFI_OP(_CFFI_OP_NOOP, 11),
/* 47 */ _CFFI_OP(_CFFI_OP_ENUM, 5), // enum evm_update_key
/* 48 */ _CFFI_OP(_CFFI_OP_NOOP, 43),
/* 49 */ _CFFI_OP(_CFFI_OP_NOOP, 43),
/* 50 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 51 */ _CFFI_OP(_CFFI_OP_FUNCTION, 88), // void()(struct evm_instance *)
/* 52 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 53 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 54 */ _CFFI_OP(_CFFI_OP_FUNCTION, 88), // void()(struct evm_instance *, enum evm_mode, struct evm_uint256be, uint8_t const *, size_t)
/* 55 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 56 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 57 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 58 */ _CFFI_OP(_CFFI_OP_NOOP, 16),
/* 59 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 28),
/* 60 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 61 */ _CFFI_OP(_CFFI_OP_FUNCTION, 88), // void()(struct evm_result const *)
/* 62 */ _CFFI_OP(_CFFI_OP_POINTER, 75), // struct evm_result const *
/* 63 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 64 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 65 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // enum evm_code_status(*)(struct evm_instance *, enum evm_mode, struct evm_uint256be)
/* 66 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // enum evm_code_status
/* 67 */ _CFFI_OP(_CFFI_OP_ENUM, 4), // enum evm_result_code
/* 68 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // int(*)(struct evm_instance *, char const *, char const *)
/* 69 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 70 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // struct evm_env
/* 71 */ _CFFI_OP(_CFFI_OP_POINTER, 21), // struct evm_instance *(*)(union evm_variant(*)(struct evm_env *, enum evm_query_key, union evm_variant), void(*)(struct evm_env *, enum evm_update_key, union evm_variant, union evm_variant), int64_t(*)(struct evm_env *, enum evm_call_kind, int64_t, struct evm_uint160be, struct evm_uint256be, uint8_t const *, size_t, uint8_t *, size_t))
/* 72 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // struct evm_instance
/* 73 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // struct evm_interface
/* 74 */ _CFFI_OP(_CFFI_OP_POINTER, 28), // struct evm_result(*)(struct evm_instance *, struct evm_env *, enum evm_mode, struct evm_uint256be, uint8_t const *, size_t, int64_t, uint8_t const *, size_t, struct evm_uint256be)
/* 75 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // struct evm_result
/* 76 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22), // uint32_t
/* 77 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 78 */ _CFFI_OP(_CFFI_OP_ARRAY, 77), // uint8_t[12]
/* 79 */ (_cffi_opcode_t)(12),
/* 80 */ _CFFI_OP(_CFFI_OP_ARRAY, 77), // uint8_t[20]
/* 81 */ (_cffi_opcode_t)(20),
/* 82 */ _CFFI_OP(_CFFI_OP_ARRAY, 77), // uint8_t[32]
/* 83 */ (_cffi_opcode_t)(32),
/* 84 */ _CFFI_OP(_CFFI_OP_POINTER, 88), // void *
/* 85 */ _CFFI_OP(_CFFI_OP_POINTER, 51), // void(*)(struct evm_instance *)
/* 86 */ _CFFI_OP(_CFFI_OP_POINTER, 54), // void(*)(struct evm_instance *, enum evm_mode, struct evm_uint256be, uint8_t const *, size_t)
/* 87 */ _CFFI_OP(_CFFI_OP_POINTER, 61), // void(*)(struct evm_result const *)
/* 88 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_EVM_CALL_FAILURE(unsigned long long *o)
{
  int n = (EVM_CALL_FAILURE) <= 0;
  *o = (unsigned long long)((EVM_CALL_FAILURE) | 0);  /* check that EVM_CALL_FAILURE is an integer */
  return n;
}

static int _cffi_const_EVM_CALL(unsigned long long *o)
{
  int n = (EVM_CALL) <= 0;
  *o = (unsigned long long)((EVM_CALL) | 0);  /* check that EVM_CALL is an integer */
  return n;
}

static int _cffi_const_EVM_DELEGATECALL(unsigned long long *o)
{
  int n = (EVM_DELEGATECALL) <= 0;
  *o = (unsigned long long)((EVM_DELEGATECALL) | 0);  /* check that EVM_DELEGATECALL is an integer */
  return n;
}

static int _cffi_const_EVM_CALLCODE(unsigned long long *o)
{
  int n = (EVM_CALLCODE) <= 0;
  *o = (unsigned long long)((EVM_CALLCODE) | 0);  /* check that EVM_CALLCODE is an integer */
  return n;
}

static int _cffi_const_EVM_CREATE(unsigned long long *o)
{
  int n = (EVM_CREATE) <= 0;
  *o = (unsigned long long)((EVM_CREATE) | 0);  /* check that EVM_CREATE is an integer */
  return n;
}

static int _cffi_const_EVM_UNKNOWN(unsigned long long *o)
{
  int n = (EVM_UNKNOWN) <= 0;
  *o = (unsigned long long)((EVM_UNKNOWN) | 0);  /* check that EVM_UNKNOWN is an integer */
  return n;
}

static int _cffi_const_EVM_READY(unsigned long long *o)
{
  int n = (EVM_READY) <= 0;
  *o = (unsigned long long)((EVM_READY) | 0);  /* check that EVM_READY is an integer */
  return n;
}

static int _cffi_const_EVM_CACHED(unsigned long long *o)
{
  int n = (EVM_CACHED) <= 0;
  *o = (unsigned long long)((EVM_CACHED) | 0);  /* check that EVM_CACHED is an integer */
  return n;
}

static int _cffi_const_EVM_FRONTIER(unsigned long long *o)
{
  int n = (EVM_FRONTIER) <= 0;
  *o = (unsigned long long)((EVM_FRONTIER) | 0);  /* check that EVM_FRONTIER is an integer */
  return n;
}

static int _cffi_const_EVM_HOMESTEAD(unsigned long long *o)
{
  int n = (EVM_HOMESTEAD) <= 0;
  *o = (unsigned long long)((EVM_HOMESTEAD) | 0);  /* check that EVM_HOMESTEAD is an integer */
  return n;
}

static int _cffi_const_EVM_SLOAD(unsigned long long *o)
{
  int n = (EVM_SLOAD) <= 0;
  *o = (unsigned long long)((EVM_SLOAD) | 0);  /* check that EVM_SLOAD is an integer */
  return n;
}

static int _cffi_const_EVM_ADDRESS(unsigned long long *o)
{
  int n = (EVM_ADDRESS) <= 0;
  *o = (unsigned long long)((EVM_ADDRESS) | 0);  /* check that EVM_ADDRESS is an integer */
  return n;
}

static int _cffi_const_EVM_CALLER(unsigned long long *o)
{
  int n = (EVM_CALLER) <= 0;
  *o = (unsigned long long)((EVM_CALLER) | 0);  /* check that EVM_CALLER is an integer */
  return n;
}

static int _cffi_const_EVM_ORIGIN(unsigned long long *o)
{
  int n = (EVM_ORIGIN) <= 0;
  *o = (unsigned long long)((EVM_ORIGIN) | 0);  /* check that EVM_ORIGIN is an integer */
  return n;
}

static int _cffi_const_EVM_GAS_PRICE(unsigned long long *o)
{
  int n = (EVM_GAS_PRICE) <= 0;
  *o = (unsigned long long)((EVM_GAS_PRICE) | 0);  /* check that EVM_GAS_PRICE is an integer */
  return n;
}

static int _cffi_const_EVM_COINBASE(unsigned long long *o)
{
  int n = (EVM_COINBASE) <= 0;
  *o = (unsigned long long)((EVM_COINBASE) | 0);  /* check that EVM_COINBASE is an integer */
  return n;
}

static int _cffi_const_EVM_DIFFICULTY(unsigned long long *o)
{
  int n = (EVM_DIFFICULTY) <= 0;
  *o = (unsigned long long)((EVM_DIFFICULTY) | 0);  /* check that EVM_DIFFICULTY is an integer */
  return n;
}

static int _cffi_const_EVM_GAS_LIMIT(unsigned long long *o)
{
  int n = (EVM_GAS_LIMIT) <= 0;
  *o = (unsigned long long)((EVM_GAS_LIMIT) | 0);  /* check that EVM_GAS_LIMIT is an integer */
  return n;
}

static int _cffi_const_EVM_NUMBER(unsigned long long *o)
{
  int n = (EVM_NUMBER) <= 0;
  *o = (unsigned long long)((EVM_NUMBER) | 0);  /* check that EVM_NUMBER is an integer */
  return n;
}

static int _cffi_const_EVM_TIMESTAMP(unsigned long long *o)
{
  int n = (EVM_TIMESTAMP) <= 0;
  *o = (unsigned long long)((EVM_TIMESTAMP) | 0);  /* check that EVM_TIMESTAMP is an integer */
  return n;
}

static int _cffi_const_EVM_CODE_BY_ADDRESS(unsigned long long *o)
{
  int n = (EVM_CODE_BY_ADDRESS) <= 0;
  *o = (unsigned long long)((EVM_CODE_BY_ADDRESS) | 0);  /* check that EVM_CODE_BY_ADDRESS is an integer */
  return n;
}

static int _cffi_const_EVM_BALANCE(unsigned long long *o)
{
  int n = (EVM_BALANCE) <= 0;
  *o = (unsigned long long)((EVM_BALANCE) | 0);  /* check that EVM_BALANCE is an integer */
  return n;
}

static int _cffi_const_EVM_BLOCKHASH(unsigned long long *o)
{
  int n = (EVM_BLOCKHASH) <= 0;
  *o = (unsigned long long)((EVM_BLOCKHASH) | 0);  /* check that EVM_BLOCKHASH is an integer */
  return n;
}

static int _cffi_const_EVM_ACCOUNT_EXISTS(unsigned long long *o)
{
  int n = (EVM_ACCOUNT_EXISTS) <= 0;
  *o = (unsigned long long)((EVM_ACCOUNT_EXISTS) | 0);  /* check that EVM_ACCOUNT_EXISTS is an integer */
  return n;
}

static int _cffi_const_EVM_CALL_DEPTH(unsigned long long *o)
{
  int n = (EVM_CALL_DEPTH) <= 0;
  *o = (unsigned long long)((EVM_CALL_DEPTH) | 0);  /* check that EVM_CALL_DEPTH is an integer */
  return n;
}

static int _cffi_const_EVM_SUCCESS(unsigned long long *o)
{
  int n = (EVM_SUCCESS) <= 0;
  *o = (unsigned long long)((EVM_SUCCESS) | 0);  /* check that EVM_SUCCESS is an integer */
  return n;
}

static int _cffi_const_EVM_FAILURE(unsigned long long *o)
{
  int n = (EVM_FAILURE) <= 0;
  *o = (unsigned long long)((EVM_FAILURE) | 0);  /* check that EVM_FAILURE is an integer */
  return n;
}

static int _cffi_const_EVM_OUT_OF_GAS(unsigned long long *o)
{
  int n = (EVM_OUT_OF_GAS) <= 0;
  *o = (unsigned long long)((EVM_OUT_OF_GAS) | 0);  /* check that EVM_OUT_OF_GAS is an integer */
  return n;
}

static int _cffi_const_EVM_BAD_INSTRUCTION(unsigned long long *o)
{
  int n = (EVM_BAD_INSTRUCTION) <= 0;
  *o = (unsigned long long)((EVM_BAD_INSTRUCTION) | 0);  /* check that EVM_BAD_INSTRUCTION is an integer */
  return n;
}

static int _cffi_const_EVM_BAD_JUMP_DESTINATION(unsigned long long *o)
{
  int n = (EVM_BAD_JUMP_DESTINATION) <= 0;
  *o = (unsigned long long)((EVM_BAD_JUMP_DESTINATION) | 0);  /* check that EVM_BAD_JUMP_DESTINATION is an integer */
  return n;
}

static int _cffi_const_EVM_STACK_OVERFLOW(unsigned long long *o)
{
  int n = (EVM_STACK_OVERFLOW) <= 0;
  *o = (unsigned long long)((EVM_STACK_OVERFLOW) | 0);  /* check that EVM_STACK_OVERFLOW is an integer */
  return n;
}

static int _cffi_const_EVM_STACK_UNDERFLOW(unsigned long long *o)
{
  int n = (EVM_STACK_UNDERFLOW) <= 0;
  *o = (unsigned long long)((EVM_STACK_UNDERFLOW) | 0);  /* check that EVM_STACK_UNDERFLOW is an integer */
  return n;
}

static int _cffi_const_EVM_SSTORE(unsigned long long *o)
{
  int n = (EVM_SSTORE) <= 0;
  *o = (unsigned long long)((EVM_SSTORE) | 0);  /* check that EVM_SSTORE is an integer */
  return n;
}

static int _cffi_const_EVM_LOG(unsigned long long *o)
{
  int n = (EVM_LOG) <= 0;
  *o = (unsigned long long)((EVM_LOG) | 0);  /* check that EVM_LOG is an integer */
  return n;
}

static int _cffi_const_EVM_SELFDESTRUCT(unsigned long long *o)
{
  int n = (EVM_SELFDESTRUCT) <= 0;
  *o = (unsigned long long)((EVM_SELFDESTRUCT) | 0);  /* check that EVM_SELFDESTRUCT is an integer */
  return n;
}

static struct _cffi_externpy_s _cffi_externpy__evm_call =
  { "evm_call", (int)sizeof(int64_t) };

static int64_t evm_call(struct evm_env * a0, enum evm_call_kind a1, int64_t a2, struct evm_uint160be a3, struct evm_uint256be a4, uint8_t const * a5, size_t a6, uint8_t * a7, size_t a8)
{
  char a[72];
  char *p = a;
  *(struct evm_env * *)(p + 0) = a0;
  *(enum evm_call_kind *)(p + 8) = a1;
  *(int64_t *)(p + 16) = a2;
  *(struct evm_uint160be * *)(p + 24) = &a3;
  *(struct evm_uint256be * *)(p + 32) = &a4;
  *(uint8_t const * *)(p + 40) = a5;
  *(size_t *)(p + 48) = a6;
  *(uint8_t * *)(p + 56) = a7;
  *(size_t *)(p + 64) = a8;
  _cffi_call_python(&_cffi_externpy__evm_call, p);
  return *(int64_t *)p;
}

static struct _cffi_externpy_s _cffi_externpy__evm_query =
  { "evm_query", (int)sizeof(union evm_variant) };

static union evm_variant evm_query(struct evm_env * a0, enum evm_query_key a1, union evm_variant a2)
{
  char a[sizeof(union evm_variant) > 24 ? sizeof(union evm_variant) : 24];
  char *p = a;
  *(struct evm_env * *)(p + 0) = a0;
  *(enum evm_query_key *)(p + 8) = a1;
  *(union evm_variant * *)(p + 16) = &a2;
  _cffi_call_python(&_cffi_externpy__evm_query, p);
  return *(union evm_variant *)p;
}

static struct _cffi_externpy_s _cffi_externpy__evm_update =
  { "evm_update", 0 };

static void evm_update(struct evm_env * a0, enum evm_update_key a1, union evm_variant a2, union evm_variant a3)
{
  char a[32];
  char *p = a;
  *(struct evm_env * *)(p + 0) = a0;
  *(enum evm_update_key *)(p + 8) = a1;
  *(union evm_variant * *)(p + 16) = &a2;
  *(union evm_variant * *)(p + 24) = &a3;
  _cffi_call_python(&_cffi_externpy__evm_update, p);
}

static struct evm_interface _cffi_d_evmjit_get_interface(void)
{
  return evmjit_get_interface();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_evmjit_get_interface(PyObject *self, PyObject *noarg)
{
  struct evm_interface result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = evmjit_get_interface(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_struct((char *)&result, _cffi_type(73));
}
#else
static void _cffi_f_evmjit_get_interface(struct evm_interface *result)
{
  { *result = evmjit_get_interface(); }
}
#endif

static int _cffi_const_EVM_ABI_VERSION(unsigned long long *o)
{
  int n = (EVM_ABI_VERSION) <= 0;
  *o = (unsigned long long)((EVM_ABI_VERSION) | 0);  /* check that EVM_ABI_VERSION is an integer */
  if (!_cffi_check_int(*o, n, 0))
    n |= 2;
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_evm_interface(struct evm_interface *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->abi_version) | 0);  /* check that 'struct evm_interface.abi_version' is an integer */
  { struct evm_instance *(* *tmp)(union evm_variant(*)(struct evm_env *, enum evm_query_key, union evm_variant), void(*)(struct evm_env *, enum evm_update_key, union evm_variant, union evm_variant), int64_t(*)(struct evm_env *, enum evm_call_kind, int64_t, struct evm_uint160be, struct evm_uint256be, uint8_t const *, size_t, uint8_t *, size_t)) = &p->create; (void)tmp; }
  { void(* *tmp)(struct evm_instance *) = &p->destroy; (void)tmp; }
  { struct evm_result(* *tmp)(struct evm_instance *, struct evm_env *, enum evm_mode, struct evm_uint256be, uint8_t const *, size_t, int64_t, uint8_t const *, size_t, struct evm_uint256be) = &p->execute; (void)tmp; }
  { enum evm_code_status(* *tmp)(struct evm_instance *, enum evm_mode, struct evm_uint256be) = &p->get_code_status; (void)tmp; }
  { void(* *tmp)(struct evm_instance *, enum evm_mode, struct evm_uint256be, uint8_t const *, size_t) = &p->prepare_code; (void)tmp; }
  { int(* *tmp)(struct evm_instance *, char const *, char const *) = &p->set_option; (void)tmp; }
  { void(* *tmp)(struct evm_result const *) = &p->release; (void)tmp; }
}
struct _cffi_align_struct_evm_interface { char x; struct evm_interface y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_evm_result(struct evm_result *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { enum evm_result_code *tmp = &p->code; (void)tmp; }
  (void)((p->gas_left) | 0);  /* check that 'struct evm_result.gas_left' is an integer */
  { uint8_t const * *tmp = &p->output_data; (void)tmp; }
  (void)((p->output_size) | 0);  /* check that 'struct evm_result.output_size' is an integer */
  { void(* *tmp)(struct evm_result const *) = &p->release; (void)tmp; }
  { char const * *tmp = &p->error_message; (void)tmp; }
  { void * *tmp = &p->internal_memory; (void)tmp; }
}
struct _cffi_align_struct_evm_result { char x; struct evm_result y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_evm_uint160be(struct evm_uint160be *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { uint8_t(*tmp)[20] = &p->bytes; (void)tmp; }
}
struct _cffi_align_struct_evm_uint160be { char x; struct evm_uint160be y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_struct_evm_uint256be(struct evm_uint256be *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { uint8_t(*tmp)[32] = &p->bytes; (void)tmp; }
}
struct _cffi_align_struct_evm_uint256be { char x; struct evm_uint256be y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld_union_evm_variant(union evm_variant *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->int64) | 0);  /* check that 'union evm_variant.int64' is an integer */
  { struct evm_uint256be *tmp = &p->uint256be; (void)tmp; }
  { uint8_t(*tmp)[12] = &p->address_padding; (void)tmp; }
  { struct evm_uint160be *tmp = &p->address; (void)tmp; }
  { uint8_t const * *tmp = &p->data; (void)tmp; }
  (void)((p->data_size) | 0);  /* check that 'union evm_variant.data_size' is an integer */
}
struct _cffi_align_union_evm_variant { char x; union evm_variant y; };

static const struct _cffi_global_s _cffi_globals[] = {
  { "EVM_ABI_VERSION", (void *)_cffi_const_EVM_ABI_VERSION, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "EVM_ACCOUNT_EXISTS", (void *)_cffi_const_EVM_ACCOUNT_EXISTS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_ADDRESS", (void *)_cffi_const_EVM_ADDRESS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_BAD_INSTRUCTION", (void *)_cffi_const_EVM_BAD_INSTRUCTION, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_BAD_JUMP_DESTINATION", (void *)_cffi_const_EVM_BAD_JUMP_DESTINATION, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_BALANCE", (void *)_cffi_const_EVM_BALANCE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_BLOCKHASH", (void *)_cffi_const_EVM_BLOCKHASH, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_CACHED", (void *)_cffi_const_EVM_CACHED, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_CALL", (void *)_cffi_const_EVM_CALL, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_CALLCODE", (void *)_cffi_const_EVM_CALLCODE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_CALLER", (void *)_cffi_const_EVM_CALLER, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_CALL_DEPTH", (void *)_cffi_const_EVM_CALL_DEPTH, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_CALL_FAILURE", (void *)_cffi_const_EVM_CALL_FAILURE, _CFFI_OP(_CFFI_OP_CONSTANT_INT, -1), (void *)0 },
  { "EVM_CODE_BY_ADDRESS", (void *)_cffi_const_EVM_CODE_BY_ADDRESS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_COINBASE", (void *)_cffi_const_EVM_COINBASE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_CREATE", (void *)_cffi_const_EVM_CREATE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_DELEGATECALL", (void *)_cffi_const_EVM_DELEGATECALL, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_DIFFICULTY", (void *)_cffi_const_EVM_DIFFICULTY, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_FAILURE", (void *)_cffi_const_EVM_FAILURE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_FRONTIER", (void *)_cffi_const_EVM_FRONTIER, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_GAS_LIMIT", (void *)_cffi_const_EVM_GAS_LIMIT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_GAS_PRICE", (void *)_cffi_const_EVM_GAS_PRICE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_HOMESTEAD", (void *)_cffi_const_EVM_HOMESTEAD, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_LOG", (void *)_cffi_const_EVM_LOG, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_NUMBER", (void *)_cffi_const_EVM_NUMBER, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_ORIGIN", (void *)_cffi_const_EVM_ORIGIN, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_OUT_OF_GAS", (void *)_cffi_const_EVM_OUT_OF_GAS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_READY", (void *)_cffi_const_EVM_READY, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_SELFDESTRUCT", (void *)_cffi_const_EVM_SELFDESTRUCT, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_SLOAD", (void *)_cffi_const_EVM_SLOAD, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_SSTORE", (void *)_cffi_const_EVM_SSTORE, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_STACK_OVERFLOW", (void *)_cffi_const_EVM_STACK_OVERFLOW, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_STACK_UNDERFLOW", (void *)_cffi_const_EVM_STACK_UNDERFLOW, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_SUCCESS", (void *)_cffi_const_EVM_SUCCESS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_TIMESTAMP", (void *)_cffi_const_EVM_TIMESTAMP, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "EVM_UNKNOWN", (void *)_cffi_const_EVM_UNKNOWN, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "evm_call", (void *)&_cffi_externpy__evm_call, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 24), (void *)evm_call },
  { "evm_query", (void *)&_cffi_externpy__evm_query, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 22), (void *)evm_query },
  { "evm_update", (void *)&_cffi_externpy__evm_update, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 23), (void *)evm_update },
  { "evmjit_get_interface", (void *)_cffi_f_evmjit_get_interface, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 26), (void *)_cffi_d_evmjit_get_interface },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "abi_version", offsetof(struct evm_interface, abi_version),
                   sizeof(((struct evm_interface *)0)->abi_version),
                   _CFFI_OP(_CFFI_OP_NOOP, 76) },
  { "create", offsetof(struct evm_interface, create),
              sizeof(((struct evm_interface *)0)->create),
              _CFFI_OP(_CFFI_OP_NOOP, 71) },
  { "destroy", offsetof(struct evm_interface, destroy),
               sizeof(((struct evm_interface *)0)->destroy),
               _CFFI_OP(_CFFI_OP_NOOP, 85) },
  { "execute", offsetof(struct evm_interface, execute),
               sizeof(((struct evm_interface *)0)->execute),
               _CFFI_OP(_CFFI_OP_NOOP, 74) },
  { "get_code_status", offsetof(struct evm_interface, get_code_status),
                       sizeof(((struct evm_interface *)0)->get_code_status),
                       _CFFI_OP(_CFFI_OP_NOOP, 65) },
  { "prepare_code", offsetof(struct evm_interface, prepare_code),
                    sizeof(((struct evm_interface *)0)->prepare_code),
                    _CFFI_OP(_CFFI_OP_NOOP, 86) },
  { "set_option", offsetof(struct evm_interface, set_option),
                  sizeof(((struct evm_interface *)0)->set_option),
                  _CFFI_OP(_CFFI_OP_NOOP, 68) },
  { "release", offsetof(struct evm_interface, release),
               sizeof(((struct evm_interface *)0)->release),
               _CFFI_OP(_CFFI_OP_NOOP, 87) },
  { "code", offsetof(struct evm_result, code),
            sizeof(((struct evm_result *)0)->code),
            _CFFI_OP(_CFFI_OP_NOOP, 67) },
  { "gas_left", offsetof(struct evm_result, gas_left),
                sizeof(((struct evm_result *)0)->gas_left),
                _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "output_data", offsetof(struct evm_result, output_data),
                   sizeof(((struct evm_result *)0)->output_data),
                   _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "output_size", offsetof(struct evm_result, output_size),
                   sizeof(((struct evm_result *)0)->output_size),
                   _CFFI_OP(_CFFI_OP_NOOP, 17) },
  { "release", offsetof(struct evm_result, release),
               sizeof(((struct evm_result *)0)->release),
               _CFFI_OP(_CFFI_OP_NOOP, 87) },
  { "error_message", offsetof(struct evm_result, error_message),
                     sizeof(((struct evm_result *)0)->error_message),
                     _CFFI_OP(_CFFI_OP_NOOP, 7) },
  { "internal_memory", offsetof(struct evm_result, internal_memory),
                       sizeof(((struct evm_result *)0)->internal_memory),
                       _CFFI_OP(_CFFI_OP_NOOP, 84) },
  { "bytes", offsetof(struct evm_uint160be, bytes),
             sizeof(((struct evm_uint160be *)0)->bytes),
             _CFFI_OP(_CFFI_OP_NOOP, 80) },
  { "bytes", offsetof(struct evm_uint256be, bytes),
             sizeof(((struct evm_uint256be *)0)->bytes),
             _CFFI_OP(_CFFI_OP_NOOP, 82) },
  { "int64", offsetof(union evm_variant, int64),
             sizeof(((union evm_variant *)0)->int64),
             _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "uint256be", offsetof(union evm_variant, uint256be),
                 sizeof(((union evm_variant *)0)->uint256be),
                 _CFFI_OP(_CFFI_OP_NOOP, 3) },
  { "address_padding", offsetof(union evm_variant, address_padding),
                       sizeof(((union evm_variant *)0)->address_padding),
                       _CFFI_OP(_CFFI_OP_NOOP, 78) },
  { "address", offsetof(union evm_variant, address),
               sizeof(((union evm_variant *)0)->address),
               _CFFI_OP(_CFFI_OP_NOOP, 14) },
  { "data", offsetof(union evm_variant, data),
            sizeof(((union evm_variant *)0)->data),
            _CFFI_OP(_CFFI_OP_NOOP, 16) },
  { "data_size", offsetof(union evm_variant, data_size),
                 sizeof(((union evm_variant *)0)->data_size),
                 _CFFI_OP(_CFFI_OP_NOOP, 17) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "evm_env", 70, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "evm_instance", 72, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "evm_interface", 73, _CFFI_F_CHECK_FIELDS,
    sizeof(struct evm_interface), offsetof(struct _cffi_align_struct_evm_interface, y), 0, 8 },
  { "evm_result", 75, _CFFI_F_CHECK_FIELDS,
    sizeof(struct evm_result), offsetof(struct _cffi_align_struct_evm_result, y), 8, 7 },
  { "evm_uint160be", 14, _CFFI_F_CHECK_FIELDS,
    sizeof(struct evm_uint160be), offsetof(struct _cffi_align_struct_evm_uint160be, y), 15, 1 },
  { "evm_uint256be", 3, _CFFI_F_CHECK_FIELDS,
    sizeof(struct evm_uint256be), offsetof(struct _cffi_align_struct_evm_uint256be, y), 16, 1 },
  { "evm_variant", 43, _CFFI_F_UNION,
    sizeof(union evm_variant), offsetof(struct _cffi_align_union_evm_variant, y), 17, 6 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "evm_call_kind", 12, _cffi_prim_int(sizeof(enum evm_call_kind), ((enum evm_call_kind)-1) <= 0),
    "EVM_CALL,EVM_DELEGATECALL,EVM_CALLCODE,EVM_CREATE" },
  { "evm_code_status", 66, _cffi_prim_int(sizeof(enum evm_code_status), ((enum evm_code_status)-1) <= 0),
    "EVM_UNKNOWN,EVM_READY,EVM_CACHED" },
  { "evm_mode", 2, _cffi_prim_int(sizeof(enum evm_mode), ((enum evm_mode)-1) <= 0),
    "EVM_FRONTIER,EVM_HOMESTEAD" },
  { "evm_query_key", 42, _cffi_prim_int(sizeof(enum evm_query_key), ((enum evm_query_key)-1) <= 0),
    "EVM_SLOAD,EVM_ADDRESS,EVM_CALLER,EVM_ORIGIN,EVM_GAS_PRICE,EVM_COINBASE,EVM_DIFFICULTY,EVM_GAS_LIMIT,EVM_NUMBER,EVM_TIMESTAMP,EVM_CODE_BY_ADDRESS,EVM_BALANCE,EVM_BLOCKHASH,EVM_ACCOUNT_EXISTS,EVM_CALL_DEPTH" },
  { "evm_result_code", 67, _cffi_prim_int(sizeof(enum evm_result_code), ((enum evm_result_code)-1) <= 0),
    "EVM_SUCCESS,EVM_FAILURE,EVM_OUT_OF_GAS,EVM_BAD_INSTRUCTION,EVM_BAD_JUMP_DESTINATION,EVM_STACK_OVERFLOW,EVM_STACK_UNDERFLOW" },
  { "evm_update_key", 47, _cffi_prim_int(sizeof(enum evm_update_key), ((enum evm_update_key)-1) <= 0),
    "EVM_SSTORE,EVM_LOG,EVM_SELFDESTRUCT" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "evm_call_fn", 24 },
  { "evm_create_fn", 71 },
  { "evm_destroy_fn", 85 },
  { "evm_execute_fn", 74 },
  { "evm_get_code_status_fn", 65 },
  { "evm_prepare_code_fn", 86 },
  { "evm_query_fn", 22 },
  { "evm_release_result_fn", 87 },
  { "evm_set_option_fn", 68 },
  { "evm_update_fn", 23 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  40,  /* num_globals */
  7,  /* num_struct_unions */
  6,  /* num_enums */
  10,  /* num_typenames */
  NULL,  /* no includes */
  89,  /* num_types */
  1,  /* flags */
};

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit__evmjit(const void *p[])
{
    if (((intptr_t)p[0]) >= 0x0A03) {
        _cffi_call_python_org = (void(*)(struct _cffi_externpy_s *, char *))p[1];
    }
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit__evmjit(void) { return NULL; }
#  else
     init_evmjit(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit__evmjit(void)
{
  return _cffi_init("_evmjit", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
init_evmjit(void)
{
  _cffi_init("_evmjit", 0x2601, &_cffi_type_context);
}
#endif
